### ISSUE TITLE
Extend method for List is broken somehow

### ISSUE THREAD

**Issue by Soumalya1857** [Soumalya1857/Zarkan#2]
Extend method for list data structure is meant to be added for extending a list with any other data structure such as int, float, fucntion object or another list type of object...but the current implemented method is not working as it produces an unknown issue with random error msg
`Plz pr for the feature1 branch...the master branch didn't have the functionality yet`

**Comment by consigliere19** [comment]
I can help @Soumalya1857 . Please assign it to me.

**Comment by Soumalya1857** [comment]
Sure..plz do so
